version: "3.8"
services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    ports:
      - "3000:3000"
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
    volumes:
      - ./db:/rails/db

  db:
    image: postgres:17beta2
    container_name: looniedeals-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: looniedeals
    ports:
      - "5433:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    networks:
      - looniedeals
