# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/cateogries', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Cateogry. As you add validations to Cateogry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Cateogry.create! valid_attributes
      get cateogries_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      cateogry = Cateogry.create! valid_attributes
      get cateogry_url(cateogry)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_cateogry_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      cateogry = Cateogry.create! valid_attributes
      get edit_cateogry_url(cateogry)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Cateogry' do
        expect do
          post cateogries_url, params: { cateogry: valid_attributes }
        end.to change(Cateogry, :count).by(1)
      end

      it 'redirects to the created cateogry' do
        post cateogries_url, params: { cateogry: valid_attributes }
        expect(response).to redirect_to(cateogry_url(Cateogry.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Cateogry' do
        expect do
          post cateogries_url, params: { cateogry: invalid_attributes }
        end.to change(Cateogry, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cateogries_url, params: { cateogry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested cateogry' do
        cateogry = Cateogry.create! valid_attributes
        patch cateogry_url(cateogry), params: { cateogry: new_attributes }
        cateogry.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the cateogry' do
        cateogry = Cateogry.create! valid_attributes
        patch cateogry_url(cateogry), params: { cateogry: new_attributes }
        cateogry.reload
        expect(response).to redirect_to(cateogry_url(cateogry))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cateogry = Cateogry.create! valid_attributes
        patch cateogry_url(cateogry), params: { cateogry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested cateogry' do
      cateogry = Cateogry.create! valid_attributes
      expect do
        delete cateogry_url(cateogry)
      end.to change(Cateogry, :count).by(-1)
    end

    it 'redirects to the cateogries list' do
      cateogry = Cateogry.create! valid_attributes
      delete cateogry_url(cateogry)
      expect(response).to redirect_to(cateogries_url)
    end
  end
end
