# frozen_string_literal: true

stores = [
  { name: 'Amazon.ca', logo: 'amazon.ca.png', website: 'https://amazon.ca' },
  { name: 'Dollarama', logo: 'Dollarama.png', website: 'https://www.dollarama.com' },
  { name: 'Sephora', logo: 'Sephora.png', website: 'https://www.sephora.com/ca/en' },
  { name: 'Old Navy', logo: 'Old Navy.png', website: 'https://oldnavy.gapcanada.ca' },
  { name: 'GAP', logo: 'GAP.png', website: 'https://www.gapcanada.ca' },
  { name: 'Dominos', logo: 'Dominos.png', website: 'https://dominos.ca' },
  { name: 'IKEA', logo: 'IKEA.png', website: 'https://www.ikea.com/ca' },
  { name: 'Walmart', logo: 'Walmart.png', website: 'https://walmart.ca' },
  { name: 'Costco', logo: 'Costco.png', website: 'https://www.costco.ca' },
  { name: 'Shopperplus', logo: 'Shopperplus.png', website: 'https://www.shopperplus.ca' },
  { name: 'Lenovo', logo: 'Lenovo.png', website: 'https://www.lenovo.com/ca/en' },
  { name: 'Best Buy', logo: 'Best Buy.png', website: 'https://www.bestbuy.ca/en-ca' },
  { name: 'No Frills', logo: 'No Frills.png', website: 'https://www.nofrills.ca' },
  { name: 'American Express', logo: 'American Express.png', website: 'https://www.americanexpress.com/en-ca' },
  { name: 'Staples', logo: 'Staples.png', website: 'https://www.staples.ca' },
  { name: 'Loblaws', logo: 'Loblaws.png', website: 'https://www.loblaws.ca' },
  { name: 'Home Depot', logo: 'Home Depot.png', website: 'https://www.homedepot.ca' },
  { name: 'The Source', logo: 'The Source.png', website: 'https://www.thesource.ca' },
  { name: 'Princess Auto', logo: 'Princess Auto.png', website: 'https://www.princessauto.com' },
  { name: 'Ardene', logo: 'Ardene.png', website: 'https://www.ardene.com' },
  { name: 'Lululemon', logo: 'Lululemon.png', website: 'https://shop.lululemon.com' },
  { name: 'London Drugs', logo: 'London Drugs.png', website: 'https://www.londondrugs.com' },
  { name: 'Starbucks', logo: 'Starbucks.png', website: 'https://www.starbucks.ca' },
  { name: 'Subway', logo: 'Subway.png', website: 'https://www.subway.com/en-ca' },
  { name: "Mark's", logo: 'Marks.png', website: 'https://www.marks.com' },
  { name: 'Sport Chek', logo: 'Sport Chek.png', website: 'https://www.sportchek.ca' },
  { name: 'Skechers', logo: 'Skechers.png', website: 'https://www.skechers.ca' },
  { name: 'Eddie Bauer', logo: 'Eddie Bauer.png', website: 'https://www.eddiebauer.ca' },
  { name: 'The Bay', logo: 'The Bay.svg', website: 'https://www.thebay.com' },
  { name: 'Cineplex', logo: 'Cineplex.png', website: 'https://www.cineplex.com' },
  { name: 'Michaels Canada', logo: 'Michaels Canada.svg', website: 'https://canada.michaels.com' },
  { name: 'Tim Hortons', logo: 'Tim Hortons.png', website: 'https://www.timhortons.com' },
  { name: 'The Body Shop', logo: 'The Body Shop.png', website: 'https://www.thebodyshop.com/en-ca' },
  { name: 'Calvin Klein', logo: 'Calvin Klein.png', website: 'https://www.calvinklein.ca' },
  { name: 'Clarks', logo: 'Clarks.png', website: 'https://www.clarkscanada.com' },
  { name: 'Freshco', logo: 'Freshco.png', website: 'https://freshco.com' },
  { name: 'Le Chateau', logo: 'Le Chateau.png', website: 'https://suzyshier.com/pages/le-chateau' },
  { name: 'Suzy Shier', logo: 'Suzy Shier.png', website: 'https://suzyshier.com' },
  { name: 'Linen Chest', logo: 'Linen Chest.png', website: 'https://www.linenchest.com' },
  { name: 'Shoppers Drug Mart', logo: 'Shoppers Drug Mart.png', website: 'https://www.shoppersdrugmart.ca' },
  { name: 'Perkopolis', logo: 'Perkopolis.png', website: 'https://www.perkopolis.com' },
  { name: 'Wealthsimple', logo: 'Wealthsimple.png', website: 'https://www.wealthsimple.com' },
  { name: 'Fido', logo: 'Fido.png', website: 'https://www.fido.ca' },
  { name: 'MAC Cosmetics', logo: 'MAC Cosmetics.png', website: 'https://www.maccosmetics.ca' },
  { name: 'VIA Rail', logo: 'VIA Rail.png', website: 'https://www.viarail.ca' },
  { name: 'Air Canada', logo: 'Air Canada.png', website: 'https://aircanada.com' },
  { name: '123 Ink', logo: '123 Ink.png', website: 'https://www.123ink.ca' },
  { name: 'PrimeCables', logo: 'PrimeCables.png', website: 'https://www.primecables.ca' },
  { name: 'KFC', logo: 'KFC.png', website: 'https://www.kfc.ca' },
  { name: 'Pizza Hut', logo: 'Pizza Hut.png', website: 'https://www.pizzahut.ca' },
  { name: 'Go Transit', logo: 'Go Transit.png', website: 'https://www.gotransit.com' },
  { name: 'Aritzia', logo: 'Aritzia.png', website: 'https://www.aritzia.com' },
  { name: 'Petro Canada', logo: 'Petro Canada.png', website: 'https://www.petro-canada.ca' },
  { name: 'Mirvish.com', logo: 'Mirvish.png', website: 'https://www.mirvish.com' },
  { name: 'Logitech', logo: 'Logitech.png', website: 'https://www.logitech.com' },
  { name: 'Simplii Financial', logo: 'Simplii Financial.png', website: 'https://www.simplii.com' },
  { name: 'Samsung', logo: 'Samsung.png', website: 'https://www.samsung.com/ca' },
  { name: 'Aldo', logo: 'Aldo.png', website: 'https://www.aldoshoes.com/ca/en' },
  { name: 'Rexall', logo: 'Rexall.png', website: 'https://www.rexall.ca' },
  { name: 'Toys R Us', logo: 'Toys R Us.png', website: 'https://www.toysrus.ca' },
  { name: 'Visions Electronics', logo: 'Visions Electronics.png', website: 'https://www.visions.ca/' },
  { name: 'Bell', logo: 'Bell.png', website: 'https://www.bell.ca' },
  { name: 'Rona', logo: 'Rona.png', website: 'https://www.tntsupermarket.com' },
  { name: 'T&T Supermarket', logo: 'TnT Supermarket.png', website: '' },
  { name: 'Newegg', logo: 'Newegg.png', website: 'https://www.newegg.ca' },
  { name: 'Food Basics', logo: 'Food Basics.png', website: 'https://www.foodbasics.ca/index.en.html' },
  { name: 'Real Canadian Superstore', logo: 'Real Canadian Superstore.png', website: '' },
  { name: 'Swoop', logo: 'Swoop.png', website: 'https://www.flyswoop.com' },
  { name: 'Flair Airlines', logo: 'Flair Airlines.png', website: 'https://flyflair.com' },
  { name: 'Porter', logo: 'Porter.png', website: 'https://www.flyporter.com' },
  { name: 'Lynx Air', logo: 'Lynx Air.png', website: 'https://www.flylynx.com' },
  { name: 'Groupon', logo: 'Groupon.png', website: 'https://www.groupon.ca' },
  { name: 'WagJag', logo: 'WagJag.png', website: 'https://www.wagjag.com' },
  { name: 'PUMA', logo: 'PUMA.png', website: 'https://ca.puma.com/' },
  { name: 'Crocs', logo: 'Crocs.png', website: 'https://www.crocs.ca' },
  { name: 'Columbia', logo: 'Columbia Sportswear.png', website: 'https://www.columbiasportswear.ca' },
  { name: 'Foot Locker', logo: 'Foot Locker.png', website: 'https://www.footlocker.ca' },
  { name: 'Temu', logo: 'Temu.png', website: 'https://www.temu.com' },
  { name: 'Uniqlo', logo: 'Uniqlo.png', website: 'https://www.uniqlo.com' },
  { name: 'Rakuten', logo: 'rakuten.png', website: 'https://www.rakuten.ca' },
  { name: 'AliExpress', logo: 'AliExpress.png', website: 'https://aliexpress.com' },
  { name: 'BlueNotes', logo: 'BlueNotes.png', website: 'https://blnts.com' },
  { name: 'Borrowell', logo: 'Borrowell.png', website: 'https://borrowell.com' },
  { name: "Carter's OshKosh B'gosh", logo: 'OshKosh.png', website: 'https://www.cartersoshkosh.ca' },
  { name: 'Indigo', logo: 'Indigo.png', website: 'https://www.chapters.indigo.ca' },
  { name: 'Coach', logo: 'Coach.png', website: 'https://ca.coach.com' },
  { name: 'Coach Outlet', logo: 'Coach Outlet.png', website: 'https://ca.coachoutlet.com' },
  { name: 'Decathlon', logo: 'Decathlon.png', website: 'https://www.decathlon.ca' },
  { name: 'Uber Eats', logo: 'Uber Eats.png', website: 'https://www.ubereats.com/ca' },
  { name: 'DoorDash', logo: 'DoorDash.png', website: 'https://www.doordash.com/en-CA' },
  { name: 'Uber', logo: 'Uber.png', website: 'https://www.uber.com' },
  { name: 'DSW', logo: 'DSW.png', website: 'https://www.dsw.ca' },
  { name: 'H&M', logo: 'H&M.png', website: 'https://www2.hm.com/en_ca/index.html' },
  { name: 'Instacart', logo: 'Instacart.png', website: 'https://www.instacart.ca' },
  { name: 'Jamieson', logo: 'Jamieson.png', website: 'https://www.jamiesonvitamins.com' },
  { name: 'Keurig', logo: 'Keurig.png', website: 'https://www.keurig.ca' },
  { name: 'LEGO', logo: 'LEGO.png', website: 'https://www.lego.com/en-ca' },
  { name: "Levi's", logo: 'Levis.png', website: 'https://www.levi.com/CA' },
  { name: 'Lucky Brand', logo: 'Lucky Brand.png', website: 'https://blnts.com' },
  { name: 'Mountain Warehouse', logo: 'Mountain Warehouse.png', website: 'https://www.mountainwarehouse.com/ca' },
  { name: 'Neo Financial', logo: 'Neo Financial.png', website: 'https://www.neofinancial.com' },
  { name: 'NordVPN', logo: 'NordVPN.png', website: 'https://nordvpn.com' },
  { name: 'Scotiabank', logo: 'Scotiabank.png', website: 'https://www.scotiabank.com' },
  { name: 'Sporting Life', logo: 'Sporting Life.png', website: 'https://www.sportinglife.ca' },
  { name: 'TELUS', logo: 'TELUS.png', website: 'https://www.telus.com' },
  { name: 'Ticketmaster', logo: 'Ticketmaster.png', website: 'https://www.ticketmaster.ca' },
  { name: 'UGG', logo: 'UGG.png', website: 'https://www.ugg.com' },
  { name: 'Under Armour', logo: 'Under Armour.png', website: 'https://www.underarmour.ca' },
  { name: 'TopCashback', logo: 'TopCashback.png', website: 'https://www.topcashback.com' },

  { name: 'MEC', logo: 'MEC.png', website: 'https://www.mec.ca' },
  { name: 'Google.com', logo: 'Google.png', website: 'https://store.google.com' },
  { name: 'Canada Goose', logo: 'Canada Goose.png', website: 'https://www.canadagoose.com' },
  { name: 'Public Mobile', logo: 'Public Mobile.png', website: 'https://www.publicmobile.ca' },
  { name: 'Target', logo: 'Target.png', website: 'https://www.target.com' },
  { name: 'Govee', logo: 'Govee.png', website: 'https://ca.govee.com' },
  { name: 'Tangerine', logo: 'Tangerine.png', website: 'https://tangerine.ca' },
  { name: 'Rogers', logo: 'Rogers.png', website: 'https://www.rogers.com' },
  { name: 'Toronto Island SUP', logo: 'Toronto Island SUP.png', website: 'https://www.torontoislandsup.com' },
  { name: 'Circle K', logo: 'Circle K.png', website: 'https://www.circlek.com' },
  { name: 'Virgin Mobile', logo: 'Virgin Mobile.png', website: 'https://www.virginmobile.ca' },
  { name: 'Fizz', logo: 'Fizz.png', website: 'https://fizz.ca' },
  { name: 'Running Free', logo: 'Running Free.png', website: 'https://www.runningfree.com' },
  { name: 'PC Optimum', logo: 'PC Optimum.png', website: 'https://www.pcoptimum.ca' },
  { name: 'B&H Photo Video', logo: 'B&H Photo Video.png', website: 'https://www.bhphotovideo.com' },
  { name: 'Timberland', logo: 'Timberland.png', website: 'https://www.timberland.ca' },
  { name: 'Humble Bundle', logo: 'Humble Bundle.png', website: 'https://www.humblebundle.com' },
  { name: 'Flight Deals', logo: '', website: '' },
  { name: 'TD Bank', logo: 'TD Bank.png', website: 'https://www.td.com' },
  { name: 'CNE', logo: 'CNE.png', website: 'https://www.theex.com' },
  { name: 'Kitchen Aid', logo: 'Kitchen Aid.png', website: 'https://www.kitchenaid.ca' },
  { name: 'Apple TV+', logo: 'Apple TV.png', website: 'https://tv.apple.com' },
  { name: 'Xbox', logo: 'Xbox.png', website: 'https://www.xbox.com' },
  { name: 'Skip The Dishes', logo: 'Skip The Dishes.png', website: 'https://www.skipthedishes.com' },
  { name: 'Canada Computers', logo: 'Canada Computer.png', website: 'https://www.canadacomputers.com' },
  { name: 'HSBC', logo: 'HSBC.png', website: 'https://www.hsbc.ca' },
  { name: 'Canadian Protein', logo: 'Canadian Protein.png', website: 'https://canadianprotein.com' },
  { name: 'Freedom Mobile', logo: 'Freedom Mobile.png', website: 'https://shop.freedommobile.ca' },
  { name: 'No Store', logo: '', website: '' },
  { name: "Canada's Wonderland", logo: 'Canadas Wonderland.png', website: 'https://www.canadaswonderland.com' },
  { name: "Wendy's", logo: 'Wendys.png', website: 'https://www.wendys.com' },
  { name: 'Pizza Pizza', logo: 'Pizza Pizza.png', website: 'https://www.pizzapizza.ca' },
  { name: 'CIBC', logo: 'CIBC.png', website: 'https://www.cibc.com' },
  { name: 'RBC', logo: 'RBC.png', website: 'https://www.rbcroyalbank.com' },
  { name: 'LCBO', logo: 'LCBO.png', website: 'https://www.lcbo.com' },
  { name: 'Audible.ca', logo: 'Audibleca.png', website: 'https://www.audible.ca' },
  { name: 'Beanfield', logo: 'Beanfield.png', website: 'https://www.beanfield.com' },
  { name: 'Rates.ca', logo: 'Ratesca.png', website: 'https://rates.ca' },
  { name: 'Starlink', logo: 'Starlink.png', website: 'https://www.starlink.com' },
  { name: 'Royal Canadian International Circus', logo: 'Royal Canadian International Circus.png',
    website: 'https://www.royalcanadiancircus.ca' },
  { name: 'WestJet', logo: 'WestJet.png', website: 'https://www.westjet.com' },
  { name: 'PetSmart', logo: 'PetSmart.png', website: 'https://www.petsmart.ca' },
  { name: 'Shaw', logo: 'Shaw.png', website: '' },
  { name: 'Adidas', logo: 'Adidas.png', website: 'https://www.adidas.ca' },
  { name: 'EQ Bank', logo: 'EQ Bank.png', website: 'https://www.eqbank.ca' },
  { name: "Montana's", logo: 'Montanas.png', website: 'https://www.montanas.ca' },
  { name: 'Home Hardware', logo: 'Home Hardware.png', website: 'https://www.homehardware.ca' },
  { name: 'Bulk Barn', logo: 'Bulk Barn.png', website: 'https://www.bulkbarn.ca' },
  { name: 'Buffalo Jeans', logo: 'Buffalo.png', website: 'https://www.buffalojeans.ca' },
  { name: 'Rabba', logo: 'Rabba.png', website: 'https://rabba.com/' },
  { name: 'Bath & Body Works', logo: 'Bath Body Works.png', website: 'https://www.bathandbodyworks.ca' },
  { name: "McDonald's", logo: 'McDonalds.png', website: 'https://www.mcdonalds.com/ca/en-ca.html' },
  { name: 'GUESS', logo: 'GUESS.png', website: 'https://www.guess.com/ca/en/home' },
  { name: 'GUESS Factory', logo: 'GUESS Factory.png', website: 'https://www.guessfactory.com/ca/en/home' },
  { name: 'Harry Rosen', logo: 'Harry Rosen.png', website: 'https://www.harryrosen.com' },
  { name: 'Hush Puppies', logo: 'Hush Puppies.png', website: 'https://www.hushpuppies.com/CA/en_CA/home' },
  { name: 'IT Cosmetics', logo: 'IT Cosmetics.png', website: 'https://www.itcosmetics.ca' },
  { name: 'JBL', logo: 'JBL.png', website: 'https://ca.jbl.com' },
  { name: 'Bose', logo: 'Bose.png', website: 'https://www.bose.ca/en/home' },
  { name: 'Kate Spade', logo: 'Kate Spade.png', website: 'https://www.katespade.com' },
  { name: 'Kate Spade Outlets', logo: 'Kate Spade.png', website: 'https://www.katespadeoutletcanadas.com' },
  { name: "Leon's", logo: 'Leons.png', website: 'https://www.leons.ca' },
  { name: 'NYX Canada', logo: 'NYX Canada.png', website: 'https://www.nyxcosmetics.ca' },
  { name: 'Ray-Ban', logo: 'Ray-Ban.png' },
  { name: 'Roots', logo: 'Roots.png', website: 'https://www.roots.com' },
  { name: 'Sony', logo: 'Sony.png', website: '' },
  { name: 'The Brick', logo: 'The Brick.png', website: 'https://www.thebrick.com' },
  { name: 'Vitamix', logo: 'Vitamix.png', website: '' },
  { name: 'ZARA', logo: 'ZARA.png', website: 'https://www.zara.com/ca' },
  { name: 'Well.ca', logo: 'Wellca.png', website: 'https://well.ca' },
  { name: 'Enterprise Rent-A-Car', logo: 'Enterprise Rent-A-Car.png', website: 'https://www.enterprise.ca' },
  { name: 'CityPASS', logo: 'CityPASS.png', website: 'https://www.citypass.com' },
  { name: 'Call It Spring', logo: 'Call It Spring.png', website: 'https://www.callitspring.com/ca/en' },
  { name: 'e.l.f. Cosmetics', logo: 'e.l.f. Cosmetics.png', website: 'https://www.elfcosmetics.com' },
  { name: 'Expedia.ca', logo: 'Expediaca.png', website: 'https://www.expedia.ca' },
  { name: 'iRobot', logo: 'iRobot.png', website: 'https://www.irobot.ca' },
  { name: 'Kayak', logo: 'Kayak.png', website: 'https://www.ca.kayak.com' },
  { name: 'FlixBus', logo: 'FlixBus.png', website: 'https://www.flixbus.ca' },
  { name: 'Mega Bus', logo: 'Mega Bus.png', website: 'https://ca.megabus.com' },
  { name: 'Metro', logo: 'Metro.png', website: 'https://www.metro.ca' },
  { name: 'Taco Bell', logo: 'Taco Bell.png', website: 'https://www.tacobell.ca' },
  { name: 'Toronto Public Library', logo: 'Toronto Public Library.png',
    website: 'https://www.torontopubliclibrary.ca' },
  { name: 'Baskin Robbins', logo: 'Baskin Robbins.png', website: 'https://www.baskinrobbins.ca' },
  { name: 'Krispy Kreme', logo: 'Krispy Kreme.png', website: 'https://www.krispykreme.com' },
  { name: 'Destination Toronto', logo: 'Destination Toronto.png', website: 'https://www.destinationtoronto.com' },
  { name: 'MarbleSlab', logo: 'MarbleSlab.png', website: 'https://www.marbleslab.ca' },
  { name: 'Athleta', logo: 'Athleta.png', website: 'https://athleta.gapcanada.ca/' },
  { name: 'Disney Hotstar', logo: 'Disney Hotstar.png', website: 'https://www.hotstar.com' },
  { name: 'Niagara Parks', logo: 'Niagara Parks.png', website: 'https://www.niagaraparks.com' },

  { name: 'PRESTO', logo: 'PRESTO.png', website: 'https://www.prestocard.ca' },
  { name: 'SBI Canada Bank', logo: 'SBI Canada Bank.png', website: 'https://ca.statebank' },
  { name: 'The North Face', logo: 'The North Face.png', website: 'https://www.thenorthface.com' },
  { name: 'Nordstrom', logo: 'Nordstrom.png', website: 'https://www.nordstrom.com' },
  { name: 'DC Shoes', logo: 'DC Shoes.png', website: 'https://www.dcshoes-shop.ca' },
  { name: 'Tommy Hilfiger', logo: 'Tommy Hilfiger.png', website: 'https://usa.tommy.com/en/canada.html' },
  { name: 'WebSaver', logo: 'WebSaver.png', website: 'https://websaver.ca' },
  { name: 'T-Mobile', logo: 'T-Mobile.png', website: 'https://www.t-mobile.com' },
  { name: 'Swagbucks', logo: 'Swagbucks.png', website: 'https://www.swagbucks.com' },
  { name: 'Nintendo', logo: 'Nintendo.png', website: 'https://www.nintendo.com' },
  { name: 'aloSIM', logo: 'aloSIM.png', website: 'https://alosim.com' },
  { name: 'Kitchen Stuff Plus', logo: 'Kitchen Stuff Plus.png', website: 'https://www.kitchenstuffplus.com' },
  { name: 'Book Outlet', logo: 'Book Outlet.png', website: 'https://bookoutlet.ca' },
  { name: 'DAVIDsTEA', logo: 'DAVIDsTEA.png', website: 'https://www.davidstea.com' },
  { name: 'Famous Footwear', logo: 'Famous Footwear.png', website: 'https://www.famousfootwear.ca' },
  { name: 'G-SHOCK', logo: 'G-SHOCK.png', website: 'https://gshock.ca' },
  { name: 'HomeSense', logo: 'HomeSense.png', website: 'https://www.homesense.ca' },
  { name: 'Winners', logo: 'Winners.png', website: 'https://www.winners.ca' },
  { name: 'Marshalls', logo: 'Marshalls.png', website: 'https://www.marshalls.ca' },
  { name: "The Children's Place", logo: 'The Childrens Place.png', website: 'https://www.childrensplace.com' },
  { name: 'Gymboree', logo: 'Gymboree.png', website: 'https://www.gymboree.com' },
  { name: 'SVP Sports', logo: 'SVP Sports.jpg', website: 'https://www.svpsports.ca' },
  { name: 'Oxford Mills - Beddington', logo: 'Beddington.jpg', website: 'https://www.oxfordmillsoutlet.com' },
  { name: 'Shein', logo: 'Shein.png', website: 'https://ca.shein.com' },
  { name: 'Revolution Nutrition', logo: 'Revolution Nutrition.png', website: 'https://revolution-nutrition.com' },
  { name: 'My Protein', logo: 'My Protein.png', website: 'https://ca.myprotein.com' },
  { name: 'Chatime', logo: 'Chatime.png', website: 'https://chatime.ca' },
  { name: 'Koodo', logo: 'Koodo.png', website: 'https://www.koodomobile.com' },
  { name: 'SOREL', logo: 'SOREL.png', website: 'https://www.sorelfootwear.ca' },
  { name: 'Wayfair', logo: 'Wayfair.png', website: 'https://www.wayfair.ca' },
  { name: 'The Last Hunt', logo: 'The Last Hunt.png', website: '' },
  { name: 'Forever 21', logo: 'Forever 21.png', website: '' },
  { name: 'Merrell', logo: 'Merrell.png', website: '' },
  { name: 'American Eagle', logo: 'American Eagle.png', website: '' },
  { name: 'Dollar Tree', logo: 'Dollar Tree.png', website: '' },
  { name: 'DJI', logo: 'DJI.png', website: '' },
  { name: 'Ever New', logo: 'Ever New Canada.png', website: '' },
  { name: 'Unilever', logo: 'Unilever.png', website: '' },
  { name: 'Interactive Brokers', logo: 'Interactive Brokers.png', website: 'https://www.interactivebrokers.ca' },
  { name: 'New Balance', logo: 'New Balance.png', website: '' },
  { name: 'eBay', logo: 'eBay.png', website: '' },
  { name: 'Motherhood Maternity', logo: 'Motherhood Maternity.png', website: '' },
  { name: 'Dare Canada', logo: 'Dare Canada.png', website: '' },
  { name: 'GLOBO Shoes', logo: 'GLOBO Shoes.png', website: '' },
  { name: 'Reitmans', logo: 'Reitmans.png', website: '' },
  { name: 'Boston Pizza', logo: 'Boston Pizza.png', website: '' },
  { name: 'Air Miles', logo: 'Air Miles.png', website: '' },
  { name: 'Tbooth Wireless', logo: 'tbooth.png', website: '' },
  { name: 'Asics', logo: 'Asics.png', website: '' },
  { name: 'CAT Footwear', logo: 'CAT Footwear.png', website: '' },
  { name: 'Sampler', logo: 'Sampler.png', website: 'https://app.sampler.io' },
  { name: 'Natrel', logo: 'Natrel.png', website: 'https://www.natrel.ca' },
  { name: '2001 Audio Video', logo: '2001 Audio Video.png', website: 'https://www.2001audiovideo.com' },
  { name: 'Clifton Hill', logo: 'Clifton Hill.png', website: 'https://www.cliftonhill.com' },
  { name: 'CAA', logo: 'CAA.png', website: '' },
  { name: 'Canadian Tire', logo: 'Canadian Tire.png', website: 'https://www.canadiantire.ca' },
  { name: 'iGO', logo: 'iGO.png', website: 'https://igoelectric.ca' },
  { name: 'Farm Boy', logo: 'Farm Boy.png', website: '' },
  { name: 'Sobeys', logo: 'Sobeys.png', website: '' },
  { name: 'Joe Fresh', logo: 'Joe Fresh.png', website: '' },
  { name: 'Hello Fresh', logo: 'Hello Fresh.png', website: '' },
  { name: 'Flipp', logo: 'Flipp.png', website: '' },
  { name: 'Iqbal Halal Foods', logo: 'Iqbal Halal Foods.png', website: 'https://iqbalfoods.ca' },
  { name: 'Giant Tiger', logo: 'Giant Tiger.png', website: '' },
  { name: 'Longos', logo: 'Longos.png', website: '' },
  { name: 'Factory Direct', logo: 'Factory Direct.png', website: 'https://www.factorydirect.ca' },
  { name: 'Vistek', logo: 'Vistek.png', website: 'https://www.vistek.ca' },
  { name: 'JYSK', logo: 'JYSK.jpg', website: 'https://www.jysk.ca' },
  { name: 'Airalo', logo: 'airalo.png', website: 'https://www.airalo.com' },
  { name: 'Ashley Home', logo: 'Ashley Home.png', website: '' },
  { name: 'Saucony', logo: 'Saucony.png', website: '' },
  { name: 'Clearly', logo: 'Clearly.png', website: 'https://www.clearly.ca' },
  { name: 'Dairy Queen', logo: 'Dairy Queen.png', website: 'https://www.dairyqueen.com' },
  { name: 'Tip Top', logo: 'tiptop.png', website: 'https://www.tiptop.ca' },
  { name: 'Abercrombie & Fitch', logo: 'Abercrombie.png', website: 'https://www.abercrombie.com' },
  { name: 'Bodum', logo: 'Bodum.png', website: 'https://www.bodum.com' },
  { name: 'Dyson', logo: 'Dyson.png', website: 'https://www.dysoncanada.ca' },
  { name: 'Sherwin Williams', logo: 'Sherwin Williams.png', website: 'https://www.sherwin-williams.com' },
  { name: 'Nespresso', logo: '.png', website: '' },
  { name: '', logo: '.png', website: '' },
  { name: '', logo: '.png', website: '' },
  { name: '', logo: '.png', website: '' },
  { name: '', logo: '.png', website: '' },
  { name: '', logo: '.png', website: '' },
  { name: '', logo: '.png', website: '' },

]

puts stores
